import 'package:cloud_firestore/cloud_firestore.dart';

/// Attendance model class representing an attendance record.
///
/// This model is used to store and retrieve attendance data from Firebase Firestore.
class Attendance {
  /// Unique identifier for the attendance record (generated by Firestore)
  final String id;

  /// ID of the employee who marked attendance
  final String employeeId;

  /// Name of the employee (for display purposes)
  final String employeeName;

  /// Date when attendance was marked
  final DateTime date;

  /// Whether the employee is present (true) or absent (false)
  final bool isPresent;

  /// Timestamp when the attendance was recorded
  final DateTime createdAt;

  /// Constructor to create an Attendance instance
  Attendance({
    required this.id,
    required this.employeeId,
    required this.employeeName,
    required this.date,
    required this.isPresent,
    required this.createdAt,
  });

  /// Factory constructor to create an Attendance from Firestore document data
  factory Attendance.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;
    return Attendance(
      id: doc.id,
      employeeId: data['employeeId'] ?? '',
      employeeName: data['employeeName'] ?? '',
      date: (data['date'] as Timestamp?)?.toDate() ?? DateTime.now(),
      isPresent: data['isPresent'] ?? false,
      createdAt: (data['createdAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
    );
  }

  /// Convert Attendance to a Map for storing in Firestore
  Map<String, dynamic> toFirestore() {
    return {
      'employeeId': employeeId,
      'employeeName': employeeName,
      'date': Timestamp.fromDate(date),
      'isPresent': isPresent,
      'createdAt': Timestamp.fromDate(createdAt),
    };
  }

  /// Create a copy of Attendance with optional new values
  Attendance copyWith({
    String? id,
    String? employeeId,
    String? employeeName,
    DateTime? date,
    bool? isPresent,
    DateTime? createdAt,
  }) {
    return Attendance(
      id: id ?? this.id,
      employeeId: employeeId ?? this.employeeId,
      employeeName: employeeName ?? this.employeeName,
      date: date ?? this.date,
      isPresent: isPresent ?? this.isPresent,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  @override
  String toString() {
    return 'Attendance(id: $id, employeeId: $employeeId, employeeName: $employeeName, date: $date, isPresent: $isPresent)';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is Attendance && other.id == id;
  }

  @override
  int get hashCode => id.hashCode;
}