import 'package:cloud_firestore/cloud_firestore.dart';

/// Employee model class representing an employee in the system.
///
/// This model is used to store and retrieve employee data from Firebase Firestore.
class Employee {
  /// Unique identifier for the employee (generated by Firestore)
  final String id;

  /// Employee's full name
  final String name;

  /// Unique employee ID assigned by the organization
  final String employeeId;

  /// Department the employee belongs to
  final String department;

  /// Contact phone number
  final String contactNumber;

  /// Timestamp when the employee was registered
  final DateTime createdAt;

  /// Constructor to create an Employee instance
  Employee({
    required this.id,
    required this.name,
    required this.employeeId,
    required this.department,
    required this.contactNumber,
    required this.createdAt,
  });

  /// Factory constructor to create an Employee from Firestore document data
  factory Employee.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;
    return Employee(
      id: doc.id,
      name: data['name'] ?? '',
      employeeId: data['employeeId'] ?? '',
      department: data['department'] ?? '',
      contactNumber: data['contactNumber'] ?? '',
      createdAt: (data['createdAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
    );
  }

  /// Convert Employee to a Map for storing in Firestore
  Map<String, dynamic> toFirestore() {
    return {
      'name': name,
      'employeeId': employeeId,
      'department': department,
      'contactNumber': contactNumber,
      'createdAt': Timestamp.fromDate(createdAt),
    };
  }

  /// Create a copy of Employee with optional new values
  Employee copyWith({
    String? id,
    String? name,
    String? employeeId,
    String? department,
    String? contactNumber,
    DateTime? createdAt,
  }) {
    return Employee(
      id: id ?? this.id,
      name: name ?? this.name,
      employeeId: employeeId ?? this.employeeId,
      department: department ?? this.department,
      contactNumber: contactNumber ?? this.contactNumber,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  @override
  String toString() {
    return 'Employee(id: $id, name: $name, employeeId: $employeeId, department: $department)';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is Employee && other.id == id;
  }

  @override
  int get hashCode => id.hashCode;
}
